<?php

// custom gallery plugin 

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function custom_gallery_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function custom_gallery_add_meta_box() {

	add_meta_box(
		'custom_gallery-custom-gallery',
		__( 'custom_gallery', 'custom_gallery' ),
		'custom_gallery_html',
		'modelos',
		'side',
		'low'
	);
	add_meta_box(
		'custom_gallery-custom-gallery',
		__( 'custom_gallery', 'custom_gallery' ),
		'custom_gallery_html',
		'desarrollos',
		'side',
		'low'
	);

}
add_action( 'add_meta_boxes', 'custom_gallery_add_meta_box' );

function custom_gallery_html( $post) {
	wp_nonce_field( '_custom_gallery_nonce', 'custom_gallery_nonce' ); ?>

	<p>
		<label for="custom_gallery_code"><?php _e( 'code', 'custom_gallery' ); ?></label><br>
		<input type="text" name="custom_gallery_code" id="custom_gallery_code" value="<?php echo custom_gallery_get_meta( 'custom_gallery_code' ); ?>">
	</p><?php
}

function custom_gallery_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['custom_gallery_nonce'] ) || ! wp_verify_nonce( $_POST['custom_gallery_nonce'], '_custom_gallery_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['custom_gallery_code'] ) )
		update_post_meta( $post_id, 'custom_gallery_code', esc_attr( $_POST['custom_gallery_code'] ) );
}
add_action( 'save_post', 'custom_gallery_save' );

/*
	Usage: custom_gallery_get_meta( 'custom_gallery_code' )
*/

?>
