<?php

// metabox to associate a location to developments, models


/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function location_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function location_add_meta_box() {
	add_meta_box(
		'location-location',
		__( 'location', 'location' ),
		'location_html',
		'modelos',
		'side',
		'low'
	);
	add_meta_box(
		'location-location',
		__( 'location', 'location' ),
		'location_html',
		'desarrollos',
		'side',
		'low'
	);
	add_meta_box(
		'location-location',
		__( 'location', 'location' ),
		'location_html',
		'post',
		'side',
		'low'
	);
}
add_action( 'add_meta_boxes', 'location_add_meta_box' );

function location_html( $post) {
	wp_nonce_field( '_location_nonce', 'location_nonce' ); 

	// lang vars
	$lang = get_bloginfo('language');
	if ($lang == 'en-US') {
		$blank_value = 'Set the city';
	} else {
		$blank_value = 'Selecciona la ciudad';
	}

	// default values
	$default_01 = author_get_meta( 'location_city' );

	// query args
	$args = array('post_type' => 'cities', 'posts_per_page' => 110);

	// select field
	echo '<select name="location_city" id="location_city" style="width: 100%; margin-bottom: 10px;">';

		echo '<option value="null">'. $blank_value .'</option>';
		// start loop for city names
		$pages = get_posts( $args );
		foreach ( $pages as $page ) : setup_postdata( $page );
		// values
		$city_name = $page->post_title;
		$city_ID   = $page->ID;

		if ( $city_ID == $default_01 ) {
			echo '<option value="'. $city_ID .'" selected>'. $city_name .'</option>';
		} else {
			echo '<option value="'. $city_ID .'">'. $city_name .'</option>';
		}

		endforeach; 
	    wp_reset_postdata();

	echo '</select>';

}

function location_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['location_nonce'] ) || ! wp_verify_nonce( $_POST['location_nonce'], '_location_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['location_city'] ) )
		update_post_meta( $post_id, 'location_city', esc_attr( $_POST['location_city'] ) );
}
add_action( 'save_post', 'location_save' );

/*
	Usage: location_get_meta( 'location_city' )
*/

?>